from __future__ import annotations

import json
from typing import Any


NEXT_APP_MARKERS = (
    "app/",
    "pages/",
)

NEXT_CONFIG_FILES = {
    "next.config.js",
    "next.config.mjs",
    "next.config.ts",
}


def ensure_runnable_generated_files(files: list[dict[str, Any]]) -> list[dict[str, str]]:
    normalized = [_normalize_file(file) for file in files]
    normalized = [file for file in normalized if file is not None]

    paths = {file["path"] for file in normalized}
    additions: list[dict[str, str]] = []

    if _looks_like_next_app(paths, "") and "package.json" not in paths:
        additions.append(_package_json("package.json"))
        paths.add("package.json")
    if _looks_like_next_app(paths, "frontend/") and "frontend/package.json" not in paths:
        additions.append(_package_json("frontend/package.json"))
        paths.add("frontend/package.json")

    for prefix in _next_prefixes(paths):
        additions.extend(_missing_next_support_files(paths, prefix))
        paths.update(file["path"] for file in additions)

    return _ensure_next_layout_imports(normalized + additions)


def _normalize_file(file: dict[str, Any]) -> dict[str, str] | None:
    path = str(file.get("path", "")).replace("\\", "/").removeprefix("./").strip("/")
    if not path:
        return None
    return {
        "path": path,
        "language": str(file.get("language", "text")),
        "content": str(file.get("content", "")),
    }


def _looks_like_next_app(paths: set[str], prefix: str) -> bool:
    if any(f"{prefix}{config}" in paths for config in NEXT_CONFIG_FILES):
        return True
    return any(path.startswith(f"{prefix}{marker}") for marker in NEXT_APP_MARKERS for path in paths)


def _next_prefixes(paths: set[str]) -> list[str]:
    prefixes: list[str] = []
    if _looks_like_next_app(paths, ""):
        prefixes.append("")
    if _looks_like_next_app(paths, "frontend/"):
        prefixes.append("frontend/")
    return prefixes


def _missing_next_support_files(paths: set[str], prefix: str) -> list[dict[str, str]]:
    additions: list[dict[str, str]] = []
    has_typescript = any(path.startswith(prefix) and path.endswith((".ts", ".tsx")) for path in paths)
    has_app_dir = any(path.startswith(f"{prefix}app/") for path in paths)

    if has_app_dir and f"{prefix}app/layout.tsx" not in paths:
        additions.append(
            {
                "path": f"{prefix}app/layout.tsx",
                "language": "tsx",
                "content": (
                    "import type { Metadata } from 'next';\n"
                    "import './globals.css';\n\n"
                    "export const metadata: Metadata = {\n"
                    "  title: 'Generated DevTeam App',\n"
                    "  description: 'Starter app generated by DevTeam AI',\n"
                    "};\n\n"
                    "export default function RootLayout({ children }: { children: React.ReactNode }) {\n"
                    "  return (\n"
                    "    <html lang=\"en\">\n"
                    "      <body>{children}</body>\n"
                    "    </html>\n"
                    "  );\n"
                    "}\n"
                ),
            }
        )
    if has_app_dir and f"{prefix}app/globals.css" not in paths:
        additions.append(
            {
                "path": f"{prefix}app/globals.css",
                "language": "css",
                "content": default_next_globals_css(),
            }
        )
    if has_app_dir and f"{prefix}app/page.tsx" not in paths and f"{prefix}app/page.jsx" not in paths:
        additions.append(
            {
                "path": f"{prefix}app/page.tsx",
                "language": "tsx",
                "content": default_next_page_tsx(),
            }
        )
    if has_typescript and f"{prefix}tsconfig.json" not in paths:
        additions.append(
            {
                "path": f"{prefix}tsconfig.json",
                "language": "json",
                "content": json.dumps(_next_tsconfig(), indent=2) + "\n",
            }
        )
    if has_typescript and f"{prefix}next-env.d.ts" not in paths:
        additions.append(
            {
                "path": f"{prefix}next-env.d.ts",
                "language": "typescript",
                "content": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n\n// This file is generated by Next.js.\n",
            }
        )
    if not any(f"{prefix}{config}" in paths for config in NEXT_CONFIG_FILES):
        additions.append(
            {
                "path": f"{prefix}next.config.js",
                "language": "javascript",
                "content": "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\n\nmodule.exports = nextConfig;\n",
            }
        )
    return additions


def _ensure_next_layout_imports(files: list[dict[str, str]]) -> list[dict[str, str]]:
    globals_paths = {file["path"] for file in files if file["path"].endswith("app/globals.css")}
    if not globals_paths:
        return files

    updated: list[dict[str, str]] = []
    for file in files:
        if file["path"].endswith("app/layout.tsx") and "globals.css" not in file["content"]:
            updated.append({**file, "content": "import './globals.css';\n" + file["content"]})
        else:
            updated.append(file)
    return updated


def default_next_page_tsx() -> str:
    return """const features = [
  {
    title: 'Plan the work',
    body: 'Turn the approved requirements into a clear, prioritized implementation path.',
  },
  {
    title: 'Track progress',
    body: 'Use focused cards, statuses, and next steps to keep the MVP moving.',
  },
  {
    title: 'Ship confidently',
    body: 'Connect API contracts, validation notes, and test coverage before launch.',
  },
];

export default function Page() {
  return (
    <main className="app-shell">
      <section className="hero">
        <p className="eyebrow">Generated Starter</p>
        <h1>Build the MVP with a clean, ready-to-style foundation.</h1>
        <p className="hero-copy">
          This scaffold includes responsive layout, accessible controls, and a visual system you can extend as the generated plan becomes product code.
        </p>
        <div className="actions">
          <a className="button primary" href="#features">View features</a>
          <a className="button secondary" href="#features">Explore starter</a>
        </div>
      </section>

      <section className="feature-grid" id="features" aria-label="Starter features">
        {features.map((feature) => (
          <article className="card" key={feature.title}>
            <h2>{feature.title}</h2>
            <p>{feature.body}</p>
          </article>
        ))}
      </section>
    </main>
  );
}
"""


def default_next_globals_css() -> str:
    return """:root {
  color-scheme: light;
  --background: #f8fafc;
  --surface: #ffffff;
  --surface-muted: #eef6ff;
  --text: #0f172a;
  --muted: #475569;
  --border: #dbe4ef;
  --primary: #0369a1;
  --primary-dark: #0f3f66;
  --accent: #10b981;
  --shadow: 0 18px 45px rgba(15, 23, 42, 0.08);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background:
    radial-gradient(circle at top left, rgba(16, 185, 129, 0.12), transparent 28rem),
    linear-gradient(180deg, #f8fbff 0%, var(--background) 55%, #eef6ff 100%);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

a {
  color: inherit;
}

button,
a[href] {
  cursor: pointer;
}

.app-shell {
  min-height: 100vh;
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 56px 0;
}

.hero {
  display: grid;
  gap: 18px;
  padding: clamp(32px, 6vw, 72px);
  border: 1px solid var(--border);
  border-radius: 24px;
  background: rgba(255, 255, 255, 0.88);
  box-shadow: var(--shadow);
}

.eyebrow {
  width: fit-content;
  margin: 0;
  padding: 6px 10px;
  border: 1px solid #bae6fd;
  border-radius: 999px;
  background: #ecfeff;
  color: var(--primary);
  font-size: 0.75rem;
  font-weight: 800;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

h1,
h2,
p {
  margin-top: 0;
}

h1 {
  max-width: 820px;
  margin-bottom: 0;
  font-size: clamp(2.5rem, 7vw, 4.75rem);
  line-height: 0.98;
  letter-spacing: 0;
}

.hero-copy {
  max-width: 720px;
  margin-bottom: 0;
  color: var(--muted);
  font-size: 1.08rem;
  line-height: 1.7;
}

.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 8px;
}

.button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 44px;
  padding: 0 18px;
  border-radius: 10px;
  font-weight: 800;
  text-decoration: none;
  transition: transform 160ms ease, box-shadow 160ms ease, background 160ms ease;
}

.button:hover {
  transform: translateY(-1px);
}

.button.primary {
  background: var(--text);
  color: #fff;
  box-shadow: 0 12px 28px rgba(15, 23, 42, 0.18);
}

.button.secondary {
  border: 1px solid var(--border);
  background: var(--surface);
  color: var(--primary-dark);
}

.feature-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
  margin-top: 18px;
}

.card {
  min-height: 180px;
  padding: 22px;
  border: 1px solid var(--border);
  border-radius: 18px;
  background: var(--surface);
  box-shadow: 0 10px 30px rgba(15, 23, 42, 0.06);
}

.card h2 {
  margin-bottom: 10px;
  font-size: 1.1rem;
}

.card p {
  margin-bottom: 0;
  color: var(--muted);
  line-height: 1.6;
}

input,
select,
textarea {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 10px 12px;
  color: var(--text);
  font: inherit;
}

@media (max-width: 760px) {
  .app-shell {
    width: min(100% - 24px, 1120px);
    padding: 28px 0;
  }

  .hero {
    border-radius: 18px;
    padding: 28px;
  }

  .feature-grid {
    grid-template-columns: 1fr;
  }
}
"""


def _package_json(path: str) -> dict[str, str]:
    return {
        "path": path,
        "language": "json",
        "content": json.dumps(
            {
                "name": "devteam-generated-project",
                "version": "0.1.0",
                "private": True,
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "typecheck": "tsc --noEmit",
                },
                "dependencies": {
                    "next": "latest",
                    "react": "latest",
                    "react-dom": "latest",
                },
                "devDependencies": {
                    "@types/node": "latest",
                    "@types/react": "latest",
                    "@types/react-dom": "latest",
                    "typescript": "latest",
                },
            },
            indent=2,
        )
        + "\n",
    }


def _next_tsconfig() -> dict[str, Any]:
    return {
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {"@/*": ["./*"]},
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }
